Repository fossasia/pslab-app, pull requests merged in 2018-07, with the labels that each got.

#1154 feat: solved capacitance bugs
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Labels: review-required

#1134 fix: Improvements in Sensors instrument
  app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
  app/src/main/res/layout/sensor_main.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1162 feat: included the documentation of square and PWM wave
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/drawable-hdpi/wav_gen_square_img.png
  app/src/main/res/layout/activity_wave_generator_main.xml
  app/src/main/res/layout/btm_sheet_wavegen_custom.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1114 feat: oscilloscope bottom sheet guide
  app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
  app/src/main/res/layout/activity_oscilloscope.xml
  app/src/main/res/layout/bottom_sheet_oscilloscope.xml
  app/src/main/res/values/dimens.xml
Labels: review-required

#1151 feat: new icon for Compass intrument
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/drawable/tile_icon_compass.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1168 feat:added units to capacitance measurement
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
Labels: review-required

#1129 feat: csv logging
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/others/CSVLogger.java
  app/src/main/res/drawable/menu_icon_save.xml
  app/src/main/res/menu/data_log_menu.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1161 fix: Solved the bug in setting mode for Single Channel in Logic Analyzer
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1169 fix: Solved the bugs in Carousel Picker
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
  app/src/main/res/layout/logic_analyzer_logic_lines.xml
Labels: review-required

#1185 fix: Sensor label duplicates
  app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
Labels: review-required

#1187 feat: included the location in csv file
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
  app/src/main/res/values/strings.xml
Labels: review-required

#1159 feat: Added Three Channel Mode functionality in Logic Analyzer instrument
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1186 fix: Solved issue of rising and falling edges in Logic Analyzer
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1208 Placed the buttons below textbox to avoid block.
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
  app/src/main/res/layout/activity_power_source.xml
  app/src/main/res/values/dimens.xml
Labels: review-required

#1211 feat: added osm maps
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/activity/MapsActivity.java
  app/src/main/res/drawable/menu_icon_map.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/menu/data_log_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#1216 fix: Solved the issue of app crash while pressing Autoscan button in Sensors instrument
  app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
Labels: review-required

#1205 feat: new layout for multimeter
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
  app/src/main/res/drawable-mdpi/rectangle_border_black.xml
  app/src/main/res/drawable-mdpi/rectangle_border_black2.xml
  app/src/main/res/drawable/capacitor.png
  app/src/main/res/drawable/knob.xml
  app/src/main/res/drawable/knob_lines.xml
  app/src/main/res/layout/activity_multimeter.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Priority: High, WIP, review-required

#1219 feat: merged feedback section into report issues and changed google form
  app/src/main/res/values/strings.xml
Labels: review-required

#1093 feat: TSL2561 sensor integration with lux meter
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/res/layout/fragment_lux_meter_config.xml
  app/src/main/res/values/strings.xml
Labels: Priority: High, review-required

#1218 feat: added snackbar and csv file delete option
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/others/CSVLogger.java
  app/src/main/java/org/fossasia/pslab/others/CustomSnackBar.java
  app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
  app/src/main/res/layout/activity_lux_main.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review-required

#1179 feat: Adding barometer to the instrument section
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/Barometer_activity.java
  app/src/main/java/org/fossasia/pslab/fragment/BarometerFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/drawable/tile_barometer.xml
  app/src/main/res/layout/activity_barometer.xml
  app/src/main/res/layout/activity_barometer_main.xml
  app/src/main/res/layout/fragment_barometer.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1176 fix: made oscilloscope guide zoomable
  app/src/main/res/layout/bottom_sheet_oscilloscope.xml
Labels: review-required

#1230 refactor: fixed issues in multimeter
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
  app/src/main/res/drawable/knob.xml
  app/src/main/res/layout/activity_multimeter.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review-required

#1197 fix : implemented setting fragment inside setting activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
  app/src/main/java/org/fossasia/pslab/activity/SettingsActivity.java
  app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/menu/data_log_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/settings_preference_fragment.xml
Labels: conflicts, review-required

#1184 fix: multiple bug fixes in Wave Generator
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
  app/src/main/res/values/strings.xml
Labels: review-required

#1234 fix: Smoothed the data line and changed some graph properties in Lux Meter instrument
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
Labels: review-required

#1242 fix: Solved bug in working of buttons in Power Source instrument
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
Labels: review-required

#1199 feat: added switch in settings fragment to on/off location
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/activity/SettingsActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/fragment/SettingsFragment.java
  app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_preference_fragment.xml
Labels: review-required

#1249 chore: build apks from development branch
  upload-apk.sh
Labels: chore, review-required

#1212 fix: added permission check for storage in lux meter
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/res/values/strings.xml
Labels: review-required

#1265 Updating app versionName automatically
  app/build.gradle
  app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
  app/src/main/res/drawable/icon_version.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1243 feat: Added FAQs section instead of Help and Feedback
  app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/FAQFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/HelpAndFeedbackFragment.java
  app/src/main/res/drawable/ic_arrow_drop_down_black_faq.xml
  app/src/main/res/drawable/ic_arrow_drop_up_black_faq.xml
  app/src/main/res/layout/fragment_faq.xml
  app/src/main/res/layout/list_group.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1275 fix: permission for maps
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
Labels: review-required

#1276 fix: removed redundant appetize.io calls
  upload-apk.sh
Labels: review-required

#1271 feat: Made Compass instrument using built-in sensors
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/CompassActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/drawable/compass_svg.png
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1240 feat: guide for powersource
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
  app/src/main/res/drawable/menu_icon_guide.xml
  app/src/main/res/drawable/powersource_circuit.png
  app/src/main/res/layout/activity_power_source.xml
  app/src/main/res/layout/activity_powersource_layout.xml
  app/src/main/res/layout/bottom_sheet_powersource.xml
  app/src/main/res/menu/power_source_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1252 fix: Made Logic Analyzer instrument dynamic and documented the code
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/java/org/fossasia/pslab/others/LogicAnalyzerAxisFormatter.java
Labels: review-required

#1272 refactor: solved bugs in voltage measurement and resistance
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Labels: review-required

#1281 feat: Made a guide in Compass instrument to show how to calibrate the axis
  app/src/main/java/org/fossasia/pslab/activity/CompassActivity.java
  app/src/main/res/drawable/compass_help_icon.xml
  app/src/main/res/drawable/find_mobile_axis.png
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/layout/activity_compass_main.xml
  app/src/main/res/layout/bottomsheet_compass.xml
  app/src/main/res/menu/activity_compass_help_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1290 chore: upgrade app to 1.1.15
  app/build.gradle
Labels: chore, review-required

#1254 fix: Solved bug in channel selection in Two Channel Mode in Logic Analyzer
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1228 feat: added dialog with intent buttons to open other instrument
  app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/items/SquareLinearLayout.java
  app/src/main/res/drawable/icon_logic_analyzer_white.xml
  app/src/main/res/drawable/icon_multimeter_red.xml
  app/src/main/res/drawable/icon_oscilloscope_white.xml
  app/src/main/res/layout/wavegen_intent_dialog.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1302 fix: lux meter crash log from Google Play
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/res/values/strings.xml
Labels: review-required

#1309 chore: limit travis build
  .travis.yml
Labels: chore, review-required
