Repository fossasia/pslab-app, pull requests merged in 2018-10, with the labels that each got.

#1408 chore: upgrade app to 2.0.4
  app/build.gradle
Labels: chore

#1401 fix: resolved empty data bug in lux meter
  app/src/main/java/io/pslab/activity/LuxMeterActivity.java
  app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/io/pslab/others/GPSLogger.java
  app/src/main/res/values/strings.xml
Labels: review-required

#1399 Solved issues in Barometer instrument
  app/src/main/java/io/pslab/activity/BarometerActivity.java
  app/src/main/java/io/pslab/fragment/BarometerFragment.java
  app/src/main/res/layout/activity_barometer.xml
  app/src/main/res/layout/activity_barometer_main.xml
  app/src/main/res/layout/fragment_barometer.xml
Labels: review-required

#1424 chore: upgrade app to v2.0.5
  app/build.gradle
Labels: chore, deployment

#1425 chore: merge dev into master
  app/build.gradle
  app/src/main/java/io/pslab/activity/AccelerometerActivity.java
  app/src/main/java/io/pslab/activity/BarometerActivity.java
  app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
  app/src/main/java/io/pslab/activity/LuxMeterActivity.java
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/io/pslab/fragment/BarometerFragment.java
  app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/io/pslab/others/GPSLogger.java
  app/src/main/res/layout/activity_barometer.xml
  app/src/main/res/layout/activity_barometer_main.xml
  app/src/main/res/layout/fragment_barometer.xml
  app/src/main/res/layout/splash_screen.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/data_log_menu.xml
  app/src/main/res/menu/multimeter_log_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: deployment
