Repository fossasia/pslab-app, pull requests merged in 2018-12, with the labels that each got.

#1438 Updated Splash Screen Animation
  app/src/main/java/io/pslab/activity/SplashActivity.java
  app/src/main/res/layout-land/splash_screen.xml
  app/src/main/res/layout/splash_screen.xml
Labels: review-required

#1455 fix: crash in Luxmeter when no data is saved
  app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
Labels: review-required

#1464 docs: updating readme images
  docs/images/view_lux_meter.png
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/short_description
  fastlane/metadata/android/en-US/title.txt
Labels: enhancement

#1463 feat: use of white space under Luxmeter
  app/src/main/res/layout/fragment_lux_meter_data.xml
Labels: review-required

#1472 feat: stop button and upgrades to generic sensor
  app/src/main/java/io/pslab/activity/AccelerometerActivity.java
  app/src/main/java/io/pslab/activity/LuxMeterActivity.java
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/java/io/pslab/activity/SensorGraphViewActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/CSVLogger.java
  app/src/main/java/io/pslab/others/CustomSnackBar.java
  app/src/main/java/io/pslab/others/GPSLogger.java
  app/src/main/res/drawable/ic_stop_white_24dp.xml
  app/src/main/res/menu/lux_data_log_menu.xml
  app/src/main/res/values/strings.xml
Labels: Instrument: Sensors, Status: Review Rrequired, Type: Feature

#1478 refactor: Reformat code for ActionBar declaration
  app/src/main/java/io/pslab/activity/AccelerometerActivity.java
  app/src/main/java/io/pslab/activity/CompassActivity.java
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/java/io/pslab/activity/PowerSourceActivity.java
Labels: Status: Review Required

#1484 chore: upgraded app version to v2.0.7
  app/build.gradle
Labels: Chore, Deployment

#1482 chore: upgrade gradle dependencies
  .travis.yml
  app/build.gradle
  app/src/main/res/xml/lux_meter_settings.xml
  app/src/main/res/xml/settings_preference_fragment.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Chore, Deployment, Enhancement, Status: Review Required

#1489 feat: empty datalogger view
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/res/layout/activity_data_logger.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement, Status: Review Required

#1488 feat: compatibility issues in manifest
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/baro_meter_settings.xml
Labels: Enhancement, Instrument: Sensors, Status: Review Required

#1496 refactor: Remove redundant LinearLayout
  app/src/main/res/layout/pin_description_dialog.xml
Labels: Enhancement, Status: Review Required

#1494 fix: power source crash
  app/src/main/java/io/pslab/activity/PowerSourceActivity.java
Labels: Bug, Status: Review Required

#1503 chore: upgrade to v2.0.8
  app/build.gradle
Labels: Chore

#1504 chore: upgrade to v2.0.8 (#1503)
  app/build.gradle
Labels: Deployment

#1508 refactor: updated URL
  app/src/main/java/io/pslab/fragment/HomeFragment.java
Labels: Refactor, Status: Review Required

#1500 refactor: cleaned up oscilloscope source code
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/experimentsetup/Oscilloscope/OscillatorExperimentFragment.java
  app/src/main/java/io/pslab/experimentsetup/Sensors/SpeedOfSoundFragment.java
  app/src/main/res/layout/fragment_oscillator_experiment.xml
  app/src/main/res/layout/fragment_speed_of_sound.xml
Labels: Refactor, Status: Review Required

#1509 feat: pin layout back and front sides
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/fragment/PSLabPinLayoutFragment.java
  app/src/main/res/drawable/ic_pslab_pin_layout.xml
  app/src/main/res/drawable/ic_save_black_24dp.xml
  app/src/main/res/drawable/pslab_v4_colormap.png
  app/src/main/res/drawable/pslab_v4_layout.png
  app/src/main/res/drawable/pslab_v5_back_colormap.png
  app/src/main/res/drawable/pslab_v5_back_layout.png
  app/src/main/res/drawable/pslab_v5_front_colormap.png
  app/src/main/res/drawable/pslab_v5_front_layout.png
  app/src/main/res/layout/fragment_pin_layout.xml
  app/src/main/res/menu/pslab_connectivity_menu.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement, Status: Review Required

#1512 chore: upgrade to 2.0.9
  app/build.gradle
Labels: Chore, Deployment
