Repository fossasia/pslab-app, pull requests merged in 2018-06, with the labels that each got.

#944 feat: added a guide for Logic Analyzer Instrument using Alert Dialog Box
  app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
  app/src/main/res/drawable/logic_analyzer_circuit.png
  app/src/main/res/layout/custom_dialog_box.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#948 fix: Handled back button press in Webview of Home Fragment
  app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
Labels: review-required

#905 feat: added interactive pin layout diagram
  app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/PSLabPinLayoutFragment.java
  app/src/main/java/org/fossasia/pslab/items/PinDetails.java
  app/src/main/res/drawable/dialog_body_background.xml
  app/src/main/res/drawable/dialog_header_background.xml
  app/src/main/res/drawable/ic_pslab_pin_layout.xml
  app/src/main/res/drawable/pslab_v4_colormap.png
  app/src/main/res/drawable/pslab_v4_layout.png
  app/src/main/res/layout/fragment_pin_layout.xml
  app/src/main/res/layout/pin_description_dialog.xml
  app/src/main/res/menu/pslab_connectivity_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#946 test: removed MainActivity UI test
  app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java
Labels: review-required

#910 feat: created multimeter activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/layout/activity_multimeter.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#924 feat: added UI for Wave Generator Activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/animator-v21/selector_animator.xml
  app/src/main/res/drawable-hdpi/ic_pwm_pic.png
  app/src/main/res/drawable-hdpi/ic_sin.png
  app/src/main/res/drawable-hdpi/ic_square.png
  app/src/main/res/drawable-hdpi/ic_triangular.png
  app/src/main/res/drawable-mdpi/ic_pwm_pic.png
  app/src/main/res/drawable-mdpi/ic_sin.png
  app/src/main/res/drawable-mdpi/ic_square.png
  app/src/main/res/drawable-mdpi/ic_triangular.png
  app/src/main/res/drawable-xhdpi/ic_pwm_pic.png
  app/src/main/res/drawable-xhdpi/ic_sin.png
  app/src/main/res/drawable-xhdpi/ic_square.png
  app/src/main/res/drawable-xhdpi/ic_triangular.png
  app/src/main/res/drawable-xxhdpi/ic_pwm_pic.png
  app/src/main/res/drawable-xxhdpi/ic_sin.png
  app/src/main/res/drawable-xxhdpi/ic_square.png
  app/src/main/res/drawable-xxhdpi/ic_triangular.png
  app/src/main/res/drawable/btn_back_rounded.xml
  app/src/main/res/drawable/ic_arrow_drop_down_black_24dp.xml
  app/src/main/res/drawable/ic_arrow_drop_up_black_24dp.xml
  app/src/main/res/drawable/rectangle_border.xml
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_gen.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#960 feat: layout for power source instrument
  app/build.gradle
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
  app/src/main/java/org/fossasia/pslab/items/SquareImageButton.java
  app/src/main/res/drawable/control_edittext.xml
  app/src/main/res/drawable/ic_arrow_drop_down_white_24dp.xml
  app/src/main/res/drawable/ic_arrow_drop_up_white_24dp.xml
  app/src/main/res/layout/activity_power_source.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#990 refactor: reduced fluctuation of resistance in multimeter
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
Labels: ideas needed, review-required

#1006 docs: updated PR_TEMPLATE to have a checklist
  .github/PULL_REQUEST_TEMPLATE
Labels: review-required

#919 feat: Lux-meter dialog box on how to connect
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBH1750.java
  app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
  app/src/main/res/drawable/action_item_config.png
  app/src/main/res/drawable/action_item_data.png
  app/src/main/res/drawable/bh1750_schematic.png
  app/src/main/res/layout/activity_lux_meter.xml
  app/src/main/res/layout/fragment_lux_meter_config.xml
  app/src/main/res/layout/fragment_lux_meter_data.xml
  app/src/main/res/menu/activity_lux_meter_bottom_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#973 feat:implemented the working of buttons and seekbar in the waveform panel
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
  app/src/main/res/animator-v21/selector_animator.xml
  app/src/main/res/drawable/btn_back_rounded.xml
  app/src/main/res/drawable/text_color_selector.xml
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#981 feat:added guide for multimeter instrument
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
  app/src/main/res/drawable/multimeter_circuit.png
  app/src/main/res/values/strings.xml
Labels: review-required

#1007 feat: Changed the layout of Logic Analyzer
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/res/drawable/carousel_view_background.xml
  app/src/main/res/drawable/la_chart_custom_border.xml
  app/src/main/res/drawable/la_formatted_button.xml
  app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
  app/src/main/res/layout/la_time_measurement_card.xml
  app/src/main/res/layout/logic_analyzer_logic_lines.xml
  app/src/main/res/layout/modified_spinner_dropdown_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-required

#983 feat:Added the missing phase property in monitor and button for PWM.
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: review-required

#995 fix: implement functionality in power source instrument
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
  app/src/main/res/layout/activity_power_source.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#941 feat: Activity Lux meter at Instruments
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/res/drawable/action_item_config.png
  app/src/main/res/drawable/action_item_data.png
  app/src/main/res/layout/activity_lux_meter.xml
  app/src/main/res/layout/fragment_lux_meter_data.xml
  app/src/main/res/values/dimens.xml
Labels: review-required

#985 feat: Oscilloscope dialog box on how to use
  app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
  app/src/main/res/drawable/data_analysis_view.png
  app/src/main/res/drawable/mic_schematic.png
  app/src/main/res/drawable/oscilloscope_schematic.png
  app/src/main/res/drawable/timebase_view.png
  app/src/main/res/drawable/xy_plot_view.png
  app/src/main/res/layout/custom_dialog_box.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#899 docs: Adding Oscilloscope guide document
  README.md
  docs/Oscilloscope.md
  docs/images/oscilloscope_channel_params.png
  docs/images/oscilloscope_data_analysis.png
  docs/images/oscilloscope_schematic.png
  docs/images/oscilloscope_timebase_and_trigger.png
  docs/images/oscilloscope_xy_plot.png
  docs/images/screenshot_1.png
  docs/images/screenshot_2.png
  docs/images/screenshot_3.png
  docs/images/screenshot_audio_jack.png
  docs/images/screenshot_control_main.png
  docs/images/screenshot_experiment_doc.png
  docs/images/screenshot_experiment_setup.png
  docs/images/screenshot_initialization.png
  docs/images/screenshot_logical_analyzer.png
  docs/images/screenshot_multilevel_experimentlist.png
Labels: review-required

#949 feat: Lux meter Configure tab to adjust parameters
  app/build.gradle
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
  app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
  app/src/main/res/layout/fragment_lux_meter_config.xml
  app/src/main/res/layout/how_to_connect_dialog_box.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1032 refactor: fixed configure tab data pass
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
Labels: review-required

#1010 feat:added the working of all the buttons in PWM panel
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#987 fix: Changed fragments to activities for evey sensors
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
  app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorADS1115.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorBMP180.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorHMC5883L.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorMLX90614.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorMPU6050.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorMPU925X.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorSHT21.java
  app/src/main/java/org/fossasia/pslab/sensors/SensorTSL2561.java
  app/src/main/res/layout/activity_sensor.xml
  app/src/main/res/layout/fragment_lux_meter_data.xml
  app/src/main/res/layout/sensor_ads1115.xml
  app/src/main/res/layout/sensor_bmp180.xml
  app/src/main/res/layout/sensor_hmc5883l.xml
  app/src/main/res/layout/sensor_mlx90614.xml
  app/src/main/res/layout/sensor_mpu6050.xml
  app/src/main/res/layout/sensor_mpu925x.xml
  app/src/main/res/layout/sensor_sht21.xml
  app/src/main/res/layout/sensor_tsl2561.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1048 fix: uniform tile icons design update
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/drawable/tile_icon_horizontal_bars.xml
  app/src/main/res/drawable/tile_icon_logic_analyzer.xml
  app/src/main/res/drawable/tile_icon_multimeter.xml
  app/src/main/res/drawable/tile_icon_oscilloscope.xml
  app/src/main/res/drawable/tile_icon_power_source.xml
  app/src/main/res/drawable/tile_icon_sensors.xml
  app/src/main/res/drawable/tile_icon_vertical_bars.xml
  app/src/main/res/drawable/tile_icon_wave_generator.xml
  app/src/main/res/layout/application_list_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1064 fix: Fix configure fragment crash when using edit text box
  app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
Labels: review-required

#1066 refactor:solved communication issues in CH2 and CH1
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Labels: review-required

#1057 refactor: replaced png menu icon with xml
  app/src/main/res/drawable-hdpi/ic_usb_connected.png
  app/src/main/res/drawable-hdpi/ic_usb_disconnected.png
  app/src/main/res/drawable-mdpi/ic_usb_connected.png
  app/src/main/res/drawable-mdpi/ic_usb_disconnected.png
  app/src/main/res/drawable-xhdpi/ic_usb_connected.png
  app/src/main/res/drawable-xhdpi/ic_usb_disconnected.png
  app/src/main/res/drawable-xxhdpi/ic_usb_connected.png
  app/src/main/res/drawable-xxhdpi/ic_usb_disconnected.png
  app/src/main/res/drawable/ic_usb_connected.xml
  app/src/main/res/drawable/ic_usb_disconnected.xml
Labels: review-required

#1037 fix:changed the static final variable into enum
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
Labels: review-required

#1068 docs: updated README
  README.md
  docs/images/view_guide_box.png
  docs/images/view_home_screen.png
  docs/images/view_instruement_panel.png
  docs/images/view_logic_analyzer.png
  docs/images/view_lux_meter.png
  docs/images/view_navigation_drawer.png
  docs/images/view_pin_layout.png
  docs/images/view_power_source.png
  docs/images/wave_generator_view.png
Labels: review-required

#1070 refactor: cleaned up unused resources
  app/src/main/res/drawable/button_minus.png
  app/src/main/res/drawable/button_plus.png
  app/src/main/res/drawable/control_icon.png
  app/src/main/res/drawable/logic_analyzer_card.xml
  app/src/main/res/drawable/logic_analzers_icon.PNG
  app/src/main/res/drawable/multimeter_card.xml
  app/src/main/res/drawable/oscilloscope_card.xml
  app/src/main/res/drawable/osciloscope_icon.png
  app/src/main/res/drawable/power_source_card.xml
  app/src/main/res/drawable/sensors_card.xml
  app/src/main/res/drawable/wave_generator_card.xml
  app/src/main/res/drawable/wavegen.png
  app/src/main/res/drawable/wireless_sensor_icon.png
  app/src/main/res/drawable/wireless_sensor_qv_icon.PNG
  app/src/main/res/layout/about_toolbar.xml
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/settings_fragment.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: review-required

#1069 fix: Channel read errors
  app/src/main/java/org/fossasia/pslab/communication/CommandsProto.java
Labels: review-required

#1052 fix: removed leakcanary integration
  app/build.gradle
  app/src/main/java/org/fossasia/pslab/PSLabApplication.java
  app/src/main/java/org/fossasia/pslab/fragment/ChannelParametersFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java
  app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentMain.java
  app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
  app/src/main/java/org/fossasia/pslab/fragment/DataAnalysisFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocMdFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/ExperimentSetupFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/Experiments.java
  app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  build.gradle
Labels: review-required

#1036 feat:multimeter now saving its state
  app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
Labels: review-required

#1019 feat:produce sine and saw tooth waves through wave generator
  app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
Labels: review-required

#1044 feat: Implemented One Channel Mode Logic Analyzer
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
  app/src/main/java/org/fossasia/pslab/communication/digitalChannel/DigitalChannel.java
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/res/values/strings.xml
Labels: conflicts, review-required

#1050 feat:added bottomsheet guide for wave generator
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java
  app/src/main/res/drawable-hdpi/sin_wave_guide.PNG
  app/src/main/res/drawable/btn_sheet_back.xml
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator_main.xml
  app/src/main/res/layout/bottom_sheet_custom.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1077 feat: Added progress bar for Logic Analyzer Instruments
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
  app/src/main/res/layout/logic_analyzer_logic_lines.xml
Labels: review-required

#1091 Added proper documentation for Logic Analyzer Instrument
  app/src/main/res/values/strings.xml
Labels: review-required

#994 feat: Layout for the Accelerometer instrument
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/AccelerometerActivity.java
  app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java
  app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
  app/src/main/res/drawable/phone_x_axis.png
  app/src/main/res/drawable/phone_y_axis.png
  app/src/main/res/drawable/phone_z_axis.png
  app/src/main/res/drawable/tile_icon_accelerometer.xml
  app/src/main/res/layout/accelerometer_list_item.xml
  app/src/main/res/layout/activity_accelerometer.xml
  app/src/main/res/menu/accelerometer_items_menu.xml
  app/src/main/res/menu/accelerometer_sensor_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1090 feat: added bottom sheet guide for Logic Analyzer
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
  app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java
  app/src/main/res/layout-land/logic_analyzer_main_layout.xml
  app/src/main/res/layout-port/logic_analyzer_main_layout.xml
  app/src/main/res/layout/bottom_sheet_custom.xml
  app/src/main/res/values/dimens.xml
Labels: review-required

#1105 docs: update README to include Fdroid app
  README.md
Labels: review-required

#1103 Handled back press in Logic Analyzer instrument to avoid crashes
  app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1098 feat:added check for science lab device and dynamic selection of wavetype
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
Labels: review-required

#1113 docs: update readme
  README.md
Labels: review-required

#1109 feat: rapid increment/decrement feature in power source
  app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
  app/src/main/java/org/fossasia/pslab/items/SquareImageButton.java
Labels: review-required

#1119 fix: Handled DOWN gesture to collapse the guide
  app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java
Labels: review-required

#1086 feat: introduced the functionality of square wave
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1020 feat: Reading built in accelerometer and displaying values
  app/src/main/java/org/fossasia/pslab/activity/AccelerometerActivity.java
  app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java
  app/src/main/res/layout/accelerometer_list_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1120 Adding bottom sheet guide to lux meter
  app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
  app/src/main/res/layout/activity_lux_main.xml
  app/src/main/res/values/strings.xml
Labels: review-required

#1082 feat: Chart plot the acceleration values in three axes
  app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java
  app/src/main/res/layout/accelerometer_list_item.xml
Labels: review-required

#1128 docs: Lux meter documentation
  docs/Lux meter.md
  docs/images/bh1750_schematic.png
  docs/images/lux_meter_configure.png
  docs/images/lux_meter_data_1.png
  docs/images/lux_meter_data_2.png
  docs/images/lux_meter_dialog_box.png
Labels: review-required

#1117 feat: Added zoom functionality for bottom sheet guides
  app/src/main/java/org/fossasia/pslab/others/ZoomLayout.java
  app/src/main/res/layout/bottom_sheet_custom.xml
Labels: review-required

#1140 fix: Handled crash while only a single point is being fetched in Logic Analyzer
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1152 refactor: resolved voltage reading issues in AN8, SEN and CAP pins
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Labels: review-required

#1147 fix: resolved multiple creation of main activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
Labels: review-required

#1126 feat : added dynamic selection of SQ pins in PWM mode.
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/drawable/btn_back_rounded.xml
  app/src/main/res/drawable/text_color_selector.xml
Labels: review-required

#1137 fix: Added support for all pins in Singe Channel Mode for Logic Analyzer
  app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
  app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Labels: review-required

#1150 feat: implemented rapid increase decrease of seekbar value
  app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
Labels: review-required
