Repository fossasia/pslab-app, pull requests merged in 2019-01, with the labels that each got.

#1520 fix:solved the issue of multimeter crash while recording
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
Labels: Instrument: Multimeter, Status: Review Required

#1539 chore: upgrade app to v2.0.10
  app/build.gradle
Labels: Chore, Deployment

#1519 feat: Added the Permission Required Section
  README.md
Labels: Documentation, Status: Review Required
