Repository fossasia/pslab-app, pull requests merged in 2019-05, with the labels that each got.

#1698 chore: upgrade app to v2.0.11
  app/build.gradle
Labels: Chore, Deployment

#1688 Fix #1632 #1635 #1644 Continuous logging added to compass
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/CompassActivity.java
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/CompassDataFragment.java
  app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/CompassRecordables.java
  app/src/main/java/io/pslab/models/CompassData.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/drawable/tile_icon_compass_log.xml
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/menu/sensor_data_log_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Conflicts

#1683 Fix # 1622, 1653 back button added to required instruments
  app/src/main/java/io/pslab/models/PSLabSensor.java
Labels: Status: Conflicts, Status: Review Required

#1672 Fix #1636 New instrument gyroscope added
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/GyroscopeActivity.java
  app/src/main/java/io/pslab/activity/SettingsActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
  app/src/main/java/io/pslab/fragment/GyroscopeSettingsFragment.java
  app/src/main/java/io/pslab/fragment/GyroscopeViewFragment.java
  app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/GyroscopeRecordables.java
  app/src/main/java/io/pslab/models/GyroData.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/drawable/gyroscope_logdata_logo.png
  app/src/main/res/drawable/gyroscope_logo.png
  app/src/main/res/layout/fragment_gyroscope_data.xml
  app/src/main/res/layout/gyroscope_list_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/gyro_scope_settings.xml
Labels: Status: Conflicts, Status: Review Required

#1703 chore: removed unused resources
  app/src/main/res/drawable-mdpi/rectangle_border_black2.xml
  app/src/main/res/drawable/action_item_config.png
  app/src/main/res/drawable/action_item_data.png
  app/src/main/res/drawable/advance_icon.png
  app/src/main/res/drawable/bh1750.jpg
  app/src/main/res/drawable/ic_arrow_back_black_24dp.xml
  app/src/main/res/drawable/ic_arrow_drop_down_black_faq.xml
  app/src/main/res/drawable/ic_arrow_drop_up_black_faq.xml
  app/src/main/res/drawable/ic_arrow_forward_black_24dp.xml
  app/src/main/res/drawable/ic_explore_black_24dp.xml
  app/src/main/res/drawable/ic_play_circle_filled_black_24dp.xml
  app/src/main/res/drawable/icon_multimeter_red.xml
  app/src/main/res/drawable/knob_lines.xml
  app/src/main/res/drawable/logo_200.png
  app/src/main/res/drawable/record_icon.xml
  app/src/main/res/drawable/rounded_shape.xml
  app/src/main/res/drawable/sciencehacklogo.png
  app/src/main/res/drawable/sensor_icon.png
  app/src/main/res/drawable/sensor_qv_icon.png
  app/src/main/res/drawable/wip_sign.png
  app/src/main/res/layout-land/logic_analyzer_select_channel_mode.xml
  app/src/main/res/layout/accelerometer_list_item.xml
  app/src/main/res/layout/activity_accelerometer.xml
  app/src/main/res/layout/activity_accelerometer_main.xml
  app/src/main/res/layout/activity_lux_main.xml
  app/src/main/res/layout/activity_lux_meter.xml
  app/src/main/res/layout/diode_configure_dialog.xml
  app/src/main/res/layout/fragment_accelerometer_settings.xml
  app/src/main/res/layout/how_to_connect_dialog_box.xml
  app/src/main/res/layout/la_time_measurement_card.xml
  app/src/main/res/layout/logged_sensor_data.xml
  app/src/main/res/layout/logic_analyzer_select_channel.xml
  app/src/main/res/layout/logic_analyzer_select_channel_mode.xml
  app/src/main/res/layout/lux_realm_data_item.xml
  app/src/main/res/layout/single_channel_mode_la.xml
  app/src/main/res/menu/accelerometer_data_log_menu.xml
  app/src/main/res/menu/accelerometer_items_menu.xml
  app/src/main/res/menu/accelerometer_sensor_menu.xml
  app/src/main/res/menu/activity_lux_meter_bottom_navigation.xml
  app/src/main/res/menu/items_menu.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Status: Conflicts, Status: Review Required

#1677 Fix #1662 location coordinates issue solved
  app/src/main/java/io/pslab/others/GPSLogger.java
Labels: Status: Review Required

#1713 import log from local storage implemented for gyroscope and compass
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/fragment/CompassDataFragment.java
  app/src/main/res/layout/import_log_device_type_alert_layout.xml
Labels: Status: Review Required

#1724 save graph function added to compass, gyroscope and accelerometer
  app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
  app/src/main/java/io/pslab/fragment/CompassDataFragment.java
  app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/layout/fragment_accelerometer_data.xml
  app/src/main/res/layout/fragment_gyroscope_data.xml
Labels: Status: Review Required
