Repository fossasia/pslab-app, pull requests merged in 2019-08, with the labels that each got.

#1911 interface for ESP wifi module added
  app/build.gradle
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/fragment/ESPFragment.java
  app/src/main/res/drawable/ic_bluetooth.xml
  app/src/main/res/drawable/ic_wifi.xml
  app/src/main/res/layout/bluetooth_wifi_dialog_layout.xml
  app/src/main/res/layout/fragment_esp.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Status: Review Required

#1915 docs: updated fastlane metadata files
  fastlane/metadata/android/en-US/changelogs/17.txt
  fastlane/metadata/android/en-US/changelogs/18.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/short_description
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
Labels: Documentation

#1917 chore: automatic release drafting
  .github/release-drafter.yml
Labels: Chore, Documentation

#1918 chore: updated release-draft
  .github/release-drafter.yml
Labels: Chore, Documentation

#1920 docs: update readme
  README.md
Labels: Documentation

#1922 feat: logging added to mq135
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/GasSensorActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/GasSensorRecordables.java
  app/src/main/java/io/pslab/models/GasSensorData.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/layout/fragment_gas_sensor.xml
Labels: Feature

#1923 fix: unstable oscilloscope bug fixed
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Labels: Bug

#1924 feat: feature to see altitude from pressure added in Barometer
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
  app/src/main/java/io/pslab/models/BaroData.java
  app/src/main/res/layout/fragment_barometer_data.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Feature, Status: Review Required

#1932 chore: upgrade app version
  app/build.gradle
Labels: Deployment

#1941 fix: multimeter action bar fixed
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/res/menu/multimeter_log_menu.xml
Labels: Fix

#1942 fix: side navbar rearranged
  app/build.gradle
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/fragment/AboutUsFragment.java
  app/src/main/java/io/pslab/fragment/FAQFragment.java
  app/src/main/res/drawable/ic_android_black_24dp.xml
  app/src/main/res/drawable/ic_shopping_cart_black_24dp.xml
  app/src/main/res/drawable/ic_widgets_black_24dp.xml
  app/src/main/res/drawable/icon_version.xml
  app/src/main/res/layout/fragment_faq.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: Fix

#1940 fix: Actionbar added to Oscilloscope and Robotic Arm
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/java/io/pslab/fragment/OscilloscopePlaybackFragment.java
  app/src/main/res/layout/activity_oscilloscope.xml
  app/src/main/res/layout/activity_robotic_arm.xml
  app/src/main/res/layout/fragment_channel_parameters.xml
  app/src/main/res/layout/fragment_oscilloscope_playback.xml
  app/src/main/res/menu/activity_landscape_menu.xml
  app/src/main/res/menu/robotic_arm_menu.xml
  app/src/main/res/values/dimens.xml
Labels: Enhancement

#1943 feat: new Wave Generator UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator.xml
  app/src/main/res/layout/activity_wave_generator_main.xml
  app/src/main/res/layout/wave_generator_analog_mode_layout.xml
  app/src/main/res/layout/wave_generator_digital_mode_layout.xml
  app/src/main/res/layout/wave_generator_main_controls.xml
  app/src/main/res/layout/wave_generator_preview.xml
  app/src/main/res/layout/wave_generator_seekbar.xml
  app/src/main/res/layout/wave_generator_wave_controls.xml
  app/src/main/res/menu/wave_generator_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#1949 feat: Wave generator active even without pressing view button
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Labels: Fix

#1948 fix: action bar added to logic analyzer
  app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
  app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
  app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
  app/src/main/res/layout/activity_logic_analyzer.xml
  app/src/main/res/menu/logical_analyzer_menu.xml
Labels: Fix

#1927 feat: add Httphandler class
  app/src/main/java/io/pslab/communication/HttpAsyncTask.java
  app/src/main/java/io/pslab/communication/HttpHandler.java
  app/src/main/java/io/pslab/communication/PacketHandler.java
  app/src/main/java/io/pslab/fragment/ESPFragment.java
  app/src/main/java/io/pslab/interfaces/HttpCallback.java
  app/src/main/java/io/pslab/others/ScienceLabCommon.java
Labels: Feature

#1951 feat: new FAQs added
  app/src/main/java/io/pslab/fragment/FAQFragment.java
  app/src/main/res/layout/list_item.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#1952 feat: bluetooth wifi connection option moved to Connect device menu
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
  app/src/main/java/io/pslab/fragment/HomeFragment.java
  app/src/main/res/drawable/ic_bluetooth.xml
  app/src/main/res/drawable/ic_wifi.xml
  app/src/main/res/layout/bluetooth_wifi_dialog_layout.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#1957 fix: Wave generator UI changes
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/drawable/btn_back_rounded.xml
  app/src/main/res/drawable/btn_back_rounded_light.xml
  app/src/main/res/drawable/ic_arrow_left_24dp.xml
  app/src/main/res/drawable/ic_arrow_right_24dp.xml
  app/src/main/res/layout/wave_generator_analog_mode_layout.xml
  app/src/main/res/layout/wave_generator_digital_mode_layout.xml
  app/src/main/res/layout/wave_generator_main_controls.xml
  app/src/main/res/layout/wave_generator_seekbar.xml
  app/src/main/res/layout/wave_generator_wave_controls.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#1955 fix: osc main screen ui changes
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java
  app/src/main/res/layout-sw600dp/fragment_channel_parameters.xml
  app/src/main/res/layout/activity_oscilloscope.xml
  app/src/main/res/layout/fragment_channel_parameters.xml
  app/src/main/res/layout/fragment_data_analysis.xml
  app/src/main/res/layout/fragment_xyplot.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#1960 fix: scroll added to create config layout
  app/src/main/java/io/pslab/activity/CreateConfigActivity.java
  app/src/main/res/layout/activity_create_config.xml
Labels: Status: Review Required

#1958 docs: readme images changed
  README.md
  docs/images/fdroid_badge.png
  docs/images/instrument_accelerometer_view.png
  docs/images/instrument_barometer_view.png
  docs/images/instrument_compass_view.png
  docs/images/instrument_gyro_view.png
  docs/images/instrument_logic_analyzer_guide.png
  docs/images/instrument_logic_analyzer_view.png
  docs/images/instrument_logical_analyzer_view.png
  docs/images/instrument_luxmeter_guide.png
  docs/images/instrument_multi_meter_view.png
  docs/images/instrument_multimeter_view.png
  docs/images/instrument_oscilloscope_audiojack.png
  docs/images/instrument_oscilloscope_audiojack_view.png
  docs/images/instrument_oscilloscope_channel_view.png
  docs/images/instrument_oscilloscope_channelparam.png
  docs/images/instrument_oscilloscope_guide.png
  docs/images/instrument_power_source_view.png
  docs/images/instrument_robotic_arm_controller_view.png
  docs/images/instrument_robotic_arm_view.png
  docs/images/instrument_thermo_view.png
  docs/images/instrument_wave_generator_analog.png
  docs/images/instrument_wave_generator_digital.png
  docs/images/playstore_badge.png
  docs/images/view_about_us.png
  docs/images/view_create_config_file.png
  docs/images/view_data_logger.png
  docs/images/view_device_not_found.png
  docs/images/view_home_screen.png
  docs/images/view_instrument_panel.png
  docs/images/view_log_map_location.png
  docs/images/view_navigation_drawer.png
  docs/images/view_pin_layout_back.png
  docs/images/view_pin_layout_front.png
  docs/images/view_side_navigation_drawer.png
Labels: Documentation, Status: Review Required

#1962 docs: added change logs for 2.0.19
  fastlane/metadata/android/en-US/changelogs/20.txt
Labels: Documentation

#1959 feat: Add wave generator preview
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#1968 fix: degree and second symbols added to robotic arm timeline
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/res/values/strings.xml
Labels: Status: Review Required
