Repository fossasia/pslab-app, pull requests merged in 2019-06, with the labels that each got.

#1761 Fix #1759 multimeter record bug fixed
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/res/menu/multimeter_log_menu.xml
Labels: Status: Review Required

#1764 Thermometer settings added
  app/src/main/java/io/pslab/activity/SettingsActivity.java
  app/src/main/java/io/pslab/activity/ThermometerActivity.java
  app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
  app/src/main/java/io/pslab/fragment/ThermometerSettingsFragment.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/res/layout/activity_thermometer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/thermometer_settings.xml
Labels: Status: Review Required

#1755 indicator added at the top of timeline
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/res/layout/activity_robotic_arm.xml
Labels: In Progress

#1785 Visual message when no data fetched in gyroscope
  app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#1793 deploy: upgraded library versions and removed duplicates
  app/build.gradle
  build.gradle
Labels: Dependencies, Status: Review Required

#1787 Fix #1783 robotic arm save crash fixed
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Labels: Status: Review Required

#1786 fft output of ch1 working fine
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/fragment/TimebaseTriggerFragment.java
Labels: Status: Review Required

#1796 Fix #1743 working functionality of robotic arm controller added
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Labels: Status: Review Required

#1797 ch1 and ch2 simultaneous output working fine in oscilloscope
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Labels: Status: Review Required

#1801 UI of robotic arm improved
  app/src/main/res/layout/activity_robotic_arm.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Review Required

#1800 continuous cursor blinking fixed
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Labels: Status: Review Required

#1802 Fix #1650 logging added to oscilloscope
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/OscilloscopePlaybackFragment.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/OscilloscopeRecordables.java
  app/src/main/java/io/pslab/models/OscilloscopeData.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/layout/activity_oscilloscope.xml
  app/src/main/res/layout/fragment_oscilloscope_playback.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#1808 Hard coded,redundant code removed
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_oscilloscope.xml
  app/src/main/res/layout/activity_robotic_arm.xml
  app/src/main/res/layout/activity_sensor_graph_view.xml
  app/src/main/res/layout/activity_thermometer.xml
  app/src/main/res/layout/fragment_lux_meter_data.xml
  app/src/main/res/layout/fragment_timebase_tigger.xml
  app/src/main/res/layout/robotic_arm_timeline_textview.xml
  app/src/main/res/layout/sensor_list_item.xml
  app/src/main/res/layout/sensor_main.xml
  app/src/main/res/layout/sensor_mpu6050_data_card.xml
  app/src/main/res/layout/sensor_sht21.xml
  app/src/main/res/layout/servo_controller_layout.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Review Required

#1805 Guide for robotic arm
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/res/layout/activity_robotic_arm.xml
  app/src/main/res/layout/bottom_sheet_robotic_arm.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#1824 Fix #1822 logging for all channels added
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Labels: Status: Review Required

#1813 Accelerometer code refactored
  app/src/main/java/io/pslab/activity/AccelerometerActivity.java
  app/src/main/java/io/pslab/activity/GyroscopeActivity.java
  app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
  app/src/main/java/io/pslab/fragment/AccelerometerViewFragment.java
  app/src/main/java/io/pslab/fragment/GyroscopeViewFragment.java
  app/src/main/java/io/pslab/models/AccelerometerData.java
  app/src/main/res/layout/accelerometer_list_item.xml
  app/src/main/res/layout/fragment_accelerometer_data.xml
Labels: Status: Review Required

#1827 fdroid screenshots added
  fastlane/metadata/android/en-US/images/phoneScreenshots/instrument_accelerometer_view.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/instrument_barometer_view.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/instrument_logic_analyzer_view.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/instrument_luxmeter_guide.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/instrument_oscilloscope_xyplot.png
Labels: Status: Review Required

#1830 Fix #1817 fourier transform for built in mic input working fine
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Labels: Status: Review Required

#1828 Fix #1823 xy plot working fine in oscilloscope
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/fragment/XYPlotFragment.java
  app/src/main/res/layout/fragment_xyplot.xml
Labels: Status: Review Required
