Repository fossasia/pslab-app, pull requests merged in 2019-07, with the labels that each got.

#1834 Java Docs for methods in ScienceLab class
  app/src/main/java/io/pslab/communication/ScienceLab.java
Labels: In Progress

#1841 External sensor support to compass HMC5883L added
  app/src/main/java/io/pslab/activity/CompassActivity.java
  app/src/main/java/io/pslab/activity/SettingsActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/CompassDataFragment.java
  app/src/main/java/io/pslab/fragment/CompassSettingsFragment.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/compass_settings.xml
Labels: Status: Review Required

#1857 meta data added to csv file
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
  app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
  app/src/main/java/io/pslab/fragment/CompassDataFragment.java
  app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
  app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
  app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
  app/src/main/java/io/pslab/others/CSVLogger.java
  app/src/main/res/layout/import_log_device_type_alert_layout.xml
Labels: Status: Review Required

#1846 bluetooth scan interface added
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
  app/src/main/res/layout/fragment_bluetooth_scan.xml
  app/src/main/res/menu/pslab_connectivity_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#1850 Java docs added to ScienceLab class
  app/src/main/java/io/pslab/communication/ScienceLab.java
Labels: Status: Review Required

#1873 Gyroscope settings crash fixed
  app/src/main/res/xml/gyro_scope_settings.xml
Labels: Status: Review Required

#1871 robotic arm control panel now visible
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
  app/src/main/res/layout/activity_robotic_arm.xml
Labels: Status: Review Required

#1877 power source values made editable
  app/src/main/java/io/pslab/activity/PowerSourceActivity.java
  app/src/main/res/layout/activity_powersource_layout.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Review Required

#1876 import log refactor
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Labels: Status: Review Required

#1855 Update wave generator UI
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
  app/src/main/res/layout-v21/activity_wave_generator.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: In Progress, Status: Review Required

#1874 Multimeter logging / playback added
  app/src/main/java/io/pslab/activity/MultimeterActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/MultimeterRecordables.java
  app/src/main/java/io/pslab/models/MultimeterData.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/menu/multimeter_log_menu.xml
Labels: Status: Review Required

#1868 power source recording,playback and import working fine
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/PowerSourceActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/PowerSourceRecordables.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/models/PowerSourceData.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/menu/power_source_menu.xml
Labels: Status: Review Required
