Repository fossasia/pslab-app, pull requests merged in 2020-02, with the labels that each got.

#2075 Update Methods to Setup PSLab in Android Studio.
  README.md
Labels: Question, Status: Review Required

#2038 Added strings.xml in Arabic
  app/src/main/res/values-ar/strings.xml
Labels: Status: Review Required

#2054 First steps for issue #2024 - implemented the basic functionality of sound meter
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
  app/src/main/java/io/pslab/activity/SettingsActivity.java
  app/src/main/java/io/pslab/activity/SoundMeterActivity.java
  app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
  app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
  app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
  app/src/main/java/io/pslab/fragment/SoundmeterSettingsFragment.java
  app/src/main/java/io/pslab/interfaces/sensorloggers/SoundMeterRecordables.java
  app/src/main/java/io/pslab/models/PSLabSensor.java
  app/src/main/java/io/pslab/models/SoundData.java
  app/src/main/java/io/pslab/others/LocalDataLog.java
  app/src/main/res/layout/fragment_sound_meter_data.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/sound_meter_settings.xml
Labels: Status: Conflicts, Status: Review Required
