Repository fossasia/pslab-app, pull requests merged in 2021-06, with the labels that each got.

#2149 chore: substitute Travis with Github Actions
  .github/workflows/android.yml
  .travis.yml
Labels: Chore

#2199 fix: rate app navigate back to FAQ
  app/src/main/java/io/pslab/activity/MainActivity.java
Labels: Fix

#2183 feat: improve compass UI
  app/src/main/res/drawable-hdpi/compass_icon.png
  app/src/main/res/drawable-ldpi/compass_icon.png
  app/src/main/res/drawable-mdpi/compass_icon.png
  app/src/main/res/drawable-xhdpi/compass_icon.png
  app/src/main/res/drawable-xxhdpi/compass_icon.png
  app/src/main/res/drawable-xxxhdpi/compass_icon.png
  app/src/main/res/drawable/compass_svg.png
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/values/dimens.xml
Labels: Enhancement, Status: Review Required

#2214 Fix:2213 Sound paused on exiting Wave Generator Activity
  app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Labels: Fix
