Repository fossasia/pslab-app, pull requests merged in 2021-04, with the labels that each got.

#2165 Correcting spelling in guide of Oscilloscope
  app/src/main/res/values/strings.xml
Labels: Documentation

#2174 fix: done button on keyboard will connect to ESP
  app/src/main/java/io/pslab/fragment/ESPFragment.java
  app/src/main/res/layout/fragment_esp.xml
Labels: Fix

#2196 docs: icon for developers added
  app/src/main/java/io/pslab/fragment/AboutUsFragment.java
  app/src/main/res/drawable/ic_user__24dp.xml
Labels: Documentation

#2158 fix: app bar and back button in all sensor activity and add missing MPU925X sensor in sensor list index
  app/src/main/java/io/pslab/activity/SensorActivity.java
  app/src/main/java/io/pslab/sensors/SensorADS1115.java
  app/src/main/java/io/pslab/sensors/SensorBMP180.java
  app/src/main/java/io/pslab/sensors/SensorHMC5883L.java
  app/src/main/java/io/pslab/sensors/SensorMLX90614.java
  app/src/main/java/io/pslab/sensors/SensorMPU6050.java
  app/src/main/java/io/pslab/sensors/SensorMPU925X.java
  app/src/main/java/io/pslab/sensors/SensorSHT21.java
  app/src/main/java/io/pslab/sensors/SensorTSL2561.java
  app/src/main/res/drawable/circle_pause_button.xml
  app/src/main/res/drawable/circle_play_button.xml
  app/src/main/res/drawable/la_custom_border.xml
  app/src/main/res/layout/sensor_ads1115.xml
  app/src/main/res/layout/sensor_bmp180.xml
  app/src/main/res/layout/sensor_hmc5883l.xml
  app/src/main/res/layout/sensor_main.xml
  app/src/main/res/layout/sensor_mlx90614.xml
  app/src/main/res/layout/sensor_mpu6050.xml
  app/src/main/res/layout/sensor_mpu925x.xml
  app/src/main/res/layout/sensor_sht21.xml
  app/src/main/res/layout/sensor_tsl2561.xml
  app/src/main/res/values/dimens.xml
Labels: Enhancement, Status: Review Required

#2205 fix: same blutooth device shown multiple times
  app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
Labels: Fix

#2171 docs: update guide of Wave generator in strings.xml
  app/src/main/res/values/strings.xml
Labels: Documentation

#2201 Minor improvement in faq fragment
  app/src/main/res/layout/list_group.xml
Labels: Enhancement

#2185 fix: updating "Delete All Data" operation
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Labels: Enhancement

#2203 fix: change border color with red
  app/src/main/res/layout/fragment_bluetooth_scan.xml
Labels: Enhancement

#2202 fix: extract switch case statement and introduce a private method
  app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Labels: Fix, Status: Conflicts
