Repository fossasia/pslab-app, pull requests merged in 2025-07, with the labels that each got.

#2747 fix: added snackbar and small ui changes in lux meter.
  lib/constants.dart
  lib/providers/luxmeter_state_provider.dart
  lib/theme/colors.dart
  lib/view/luxmeter_screen.dart
Labels: Status: Review Required, Fix, flutter

#2743 feat: ported barometer instrument
  lib/constants.dart
  lib/main.dart
  lib/providers/barometer_state_provider.dart
  lib/view/barometer_screen.dart
  lib/view/instruments_screen.dart
  lib/view/widgets/barometer_card.dart
  lib/view/widgets/instruments_stats.dart
Labels: Status: Review Required, flutter

#2765 fix: Adapted widgets for desktop
  lib/view/barometer_screen.dart
  lib/view/luxmeter_screen.dart
  lib/view/soundmeter_screen.dart
  lib/view/widgets/barometer_card.dart
  lib/view/widgets/gauge_widget.dart
  lib/view/widgets/instruments_stats.dart
  lib/view/widgets/luxmeter_card.dart
  lib/view/widgets/soundmeter_card.dart
Labels: Status: Review Required, flutter

#2769 feat: added configuration screen for luxmeter and stored settings
  lib/constants.dart
  lib/models/luxmeter_config.dart
  lib/providers/luxmeter_config_provider.dart
  lib/providers/luxmeter_state_provider.dart
  lib/theme/colors.dart
  lib/view/luxmeter_config_screen.dart
  lib/view/luxmeter_screen.dart
  lib/view/widgets/common_scaffold_widget.dart
  lib/view/widgets/config_widgets.dart
  pubspec.yaml
Labels: Status: Review Required, flutter

#2775 feat: added Logic Analyzer
  lib/communication/digitalChannel/digital_channel.dart
  lib/communication/science_lab.dart
  lib/constants.dart
  lib/main.dart
  lib/providers/logic_analyzer_state_provider.dart
  lib/theme/colors.dart
  lib/view/instruments_screen.dart
  lib/view/logic_analyzer_screen.dart
  lib/view/widgets/logic_analyzer_channel_selection.dart
  lib/view/widgets/logic_analyzer_graph.dart
  pubspec.yaml
Labels: Feature, flutter

#2786 feat: added I2C API
  lib/communication/peripherals/i2c.dart
Labels: flutter

#2776 fix: Robotic arm UI
  lib/view/robotic_arm_screen.dart
  lib/view/widgets/robotic_arm_controls.dart
  lib/view/widgets/robotic_arm_dialog.dart
  lib/view/widgets/robotic_arm_summary.dart
  lib/view/widgets/robotic_arm_timeline.dart
  lib/view/widgets/servo_card.dart
Labels: Status: Review Required, Fix

#2785 feat: added csv functionalities
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/others/csv_service.dart
  lib/providers/luxmeter_state_provider.dart
  lib/view/logged_data_chart_screen.dart
  lib/view/logged_data_screen.dart
  lib/view/luxmeter_screen.dart
  lib/view/widgets/common_scaffold_widget.dart
  pubspec.yaml
Labels: Status: Review Required, flutter

#2800 chore(ci): update workflows to reflect repository rename to pslab-app
  .github/workflows/push-event.yml
Labels: flutter

#2792 feat: added Power Source screen
  lib/communication/commands_proto.dart
  lib/communication/peripherals/dac_channel.dart
  lib/communication/science_lab.dart
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/main.dart
  lib/providers/board_state_provider.dart
  lib/providers/power_source_state_provider.dart
  lib/theme/colors.dart
  lib/view/instruments_screen.dart
  lib/view/power_source_screen.dart
  lib/view/widgets/power_source_knob.dart
Labels: Feature, flutter
