Repository fossasia/pslab-app, pull requests merged in 2025-08, with the labels that each got.

#2811 fix: removed MANAGE_EXTERNAL_STORAGE
  android/app/src/main/AndroidManifest.xml
  lib/others/csv_service.dart
Labels: flutter

#2803 feat: added layout for the Wave Generator screen
  assets/icons/ic_sin.png
  assets/icons/ic_triangular.png
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/main.dart
  lib/view/instruments_screen.dart
  lib/view/wave_generator_screen.dart
  lib/view/widgets/analog_waveform_controls.dart
  lib/view/widgets/digital_waveform_controls.dart
  lib/view/widgets/wave_generator_graph.dart
  lib/view/widgets/wave_generator_main_controls.dart
Labels: Feature, flutter

#2789 feat: ported sensors screen and BMP180 screen
  assets/images/bmp180.jpg
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/main.dart
  lib/models/chart_data_points.dart
  lib/providers/bmp180_provider.dart
  lib/theme/colors.dart
  lib/view/bmp180_screen.dart
  lib/view/instruments_screen.dart
  lib/view/sensors_screen.dart
  lib/view/widgets/sensor_chart_widget.dart
  lib/view/widgets/sensor_controls.dart
Labels: flutter

#2761 feat: ported thermometer screen.
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/pslab/MainActivity.java
  lib/constants.dart
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/main.dart
  lib/others/temperature_service.dart
  lib/providers/thermometer_state_provider.dart
  lib/view/instruments_screen.dart
  lib/view/thermometer_screen.dart
  lib/view/widgets/thermometer_card.dart
Labels: flutter

#2796 feat: added csv functionalities in soundmeter screen.
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/providers/luxmeter_state_provider.dart
  lib/providers/soundmeter_state_provider.dart
  lib/view/logged_data_chart_screen.dart
  lib/view/logged_data_screen.dart
  lib/view/soundmeter_screen.dart
Labels: flutter

#2818 feat: added csv functionalities in gyroscope screen.
  lib/providers/gyroscope_state_provider.dart
  lib/view/compass_screen.dart
  lib/view/gyroscope_screen.dart
  lib/view/logged_data_chart_screen.dart
  lib/view/logged_data_screen.dart
Labels: flutter

#2826 feat: added functionality for Wave Generator
  assets/icons/ic_pwm_pic.png
  assets/images/sin_wave_circuit.png
  assets/images/square_wave_circuit.png
  lib/communication/science_lab.dart
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/others/wave_generator_constants.dart
  lib/providers/wave_generator_state_provider.dart
  lib/theme/colors.dart
  lib/view/wave_generator_screen.dart
  lib/view/widgets/analog_waveform_controls.dart
  lib/view/widgets/digital_waveform_controls.dart
  lib/view/widgets/wave_generator_graph.dart
  lib/view/widgets/wave_generator_main_controls.dart
Labels: Feature, flutter

#2850 fix: initialization of BoardStateProvider
  lib/providers/board_state_provider.dart
Labels: Fix, flutter

#2852 feat: added remaining Wave Generator functionality
  assets/icons/icon_logic_analyzer_white.png
  assets/icons/icon_oscilloscope_white.png
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/view/wave_generator_screen.dart
Labels: Feature, flutter

#2851 feat: added instrument guide screens
  assets/images/data_analysis_view.png
  assets/images/logic_analyzer_circuit.png
  assets/images/mic_schematic.png
  assets/images/multimeter_circuit.png
  assets/images/oscilloscope_schematic.png
  assets/images/powersource_circuit.png
  assets/images/timebase_view.png
  assets/images/xy_plot_view.png
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/view/logic_analyzer_screen.dart
  lib/view/multimeter_screen.dart
  lib/view/oscilloscope_screen.dart
  lib/view/power_source_screen.dart
  lib/view/widgets/guide_widget.dart
Labels: Feature, flutter

#2860 feat: support for large screen sizes
  ios/Runner/Info.plist
  lib/view/instruments_screen.dart
  lib/view/multimeter_screen.dart
  lib/view/oscilloscope_screen.dart
  lib/view/power_source_screen.dart
  lib/view/widgets/logic_analyzer_channel_selection.dart
  lib/view/widgets/multimeter_knob.dart
  lib/view/widgets/navigation_drawer.dart
Labels: Feature, flutter

#2863 chore: added screenshot workflows
  .github/actions/screenshot-android/action.yml
  .github/actions/screenshot-ios/action.yml
  .github/workflows/clean-screenshots.yml
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request-comment.yml
  .github/workflows/pull-request.yml
  .github/workflows/push-event.yml
  lib/providers/board_state_provider.dart
  lib/view/power_source_screen.dart
  test_integration/screenshots.dart
Labels: Chore, Status: Review Required, flutter

#2865 fix: multimeter knob UI
  lib/view/widgets/multimeter_knob.dart
Labels: Fix, flutter

#2856 feat: added firmware checks and warning
  lib/communication/commands_proto.dart
  lib/communication/packet_handler.dart
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/providers/board_state_provider.dart
  lib/view/instruments_screen.dart
Labels: Feature, flutter

#2827 feat: ported VL53L0X sensor screen.
  assets/images/vl53l0x.jpg
  lib/communication/sensors/vl53l0x.dart
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/providers/vl53l0x_provider.dart
  lib/view/sensors_screen.dart
  lib/view/vl53l0x_screen.dart
Labels: flutter

#2857 feat: Added experiment framework and created light intensity vs distance experiment.
  assets/images/lightDistance1.gif
  assets/images/lightDistance2.gif
  assets/images/lightDistance3.gif
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/main.dart
  lib/models/experiment_config.dart
  lib/models/experiment_step.dart
  lib/others/light_distance_experiment.dart
  lib/providers/experiment_provider.dart
  lib/theme/colors.dart
  lib/view/experiment_guide_screen.dart
  lib/view/experiments_screen.dart
  lib/view/luxmeter_config_screen.dart
  lib/view/luxmeter_screen.dart
  lib/view/widgets/experiment_overlay_widget.dart
  lib/view/widgets/navigation_drawer.dart
Labels: flutter

#2877 chore: selectively update versioning data
  .github/workflows/push-event.yml
Labels: Chore, flutter
