Repository fossasia/pslab-app, pull requests merged in 2025-09, with the labels that each got.

#2895 feat: fix flutter version
  .github/actions/android/action.yml
  .github/actions/common/action.yml
  .github/actions/ios/action.yml
  .github/actions/screenshot-android/action.yml
  .github/actions/screenshot-ipad/action.yml
  .github/actions/screenshot-iphone/action.yml
  .github/workflows/flutter_upgrade.yml
  pubspec.yaml
Labels: Chore, flutter

#2896 chore: add app builds for newly supported platforms
  .github/actions/linux/action.yml
  .github/actions/macos/action.yml
  .github/actions/windows/action.yml
  .github/workflows/pull-request.yml
  .github/workflows/push-event.yml
  linux/CMakeLists.txt
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  linux/my_application.cc
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
  windows/CMakeLists.txt
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
  windows/runner/Runner.rc
  windows/runner/main.cpp
  windows/runner/resources/app_icon.ico
Labels: Chore, flutter

#2917 fix: windows installer upload
  .github/workflows/push-event.yml
Labels: Chore, flutter

#2881 feat: Added Pressure vs Altitude experiment.
  assets/images/barometerExperiment1.gif
  assets/images/barometerExperiment2.gif
  assets/images/barometerExperiment3.gif
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/others/barometer_pressure_experiment.dart
  lib/view/barometer_config_screen.dart
  lib/view/barometer_screen.dart
  lib/view/experiment_guide_screen.dart
  lib/view/experiments_screen.dart
Labels: flutter

#2889 feat: added csv playback for luxmeter instrument.
  lib/providers/luxmeter_state_provider.dart
  lib/view/logged_data_screen.dart
  lib/view/luxmeter_screen.dart
Labels: flutter

#2894 feat: added csv playback for gyroscope instrument.
  lib/providers/gyroscope_state_provider.dart
  lib/view/gyroscope_screen.dart
  lib/view/logged_data_screen.dart
Labels: flutter

#2919 chore(deps): bump flusbserial to 0.2.2
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
  pubspec.lock
  pubspec.yaml
  windows/CMakeLists.txt
Labels: Chore, flutter

#2922 fix: copy changes for Instruments screen
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_he.dart
  lib/l10n/app_localizations_hi.dart
  lib/l10n/app_localizations_id.dart
  lib/l10n/app_localizations_ja.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_uk.dart
  lib/l10n/app_localizations_vi.dart
  lib/l10n/app_localizations_zh.dart
Labels: Fix, flutter

#2933 fix: map tile loading in release builds
  android/app/src/main/AndroidManifest.xml
Labels: Fix, flutter

#2943 feat: finalize Multimeter Screen
  lib/l10n/app_en.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_he.dart
  lib/l10n/app_localizations_hi.dart
  lib/l10n/app_localizations_id.dart
  lib/l10n/app_localizations_ja.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_uk.dart
  lib/l10n/app_localizations_vi.dart
  lib/l10n/app_localizations_zh.dart
  lib/models/multimeter_config.dart
  lib/providers/multimeter_config_provider.dart
  lib/providers/multimeter_state_provider.dart
  lib/view/instruments_screen.dart
  lib/view/logged_data_screen.dart
  lib/view/multimeter_config_screen.dart
  lib/view/multimeter_screen.dart
  lib/view/oscilloscope_screen.dart
Labels: Feature, flutter
