Repository fossasia/pslab-app, pull requests merged in 2025-06, with the labels that each got.

#2709 feat: added Accelerometer screen
  assets/images/phone_x_axis.png
  assets/images/phone_y_axis.png
  assets/images/phone_z_axis.png
  lib/constants.dart
  lib/main.dart
  lib/providers/accelerometer_state_provider.dart
  lib/view/accelerometer_screen.dart
  lib/view/instruments_screen.dart
  lib/view/widgets/accelerometer_card.dart
  pubspec.yaml
Labels: flutter

#2730 feat: implemented theming
  assets/images/logo.png
  lib/main.dart
  lib/others/theme.dart
  lib/view/about_us_screen.dart
  lib/view/connect_device_screen.dart
  lib/view/settings_screen.dart
  lib/view/widgets/applications_list_item.dart
  lib/view/widgets/main_scaffold_widget.dart
  lib/view/widgets/navigation_drawer.dart
Labels: Status: Review Required, flutter

#2740 feat: added support for wireless communication using ESP01
  assets/icons/ic_wifi_connected.png
  assets/icons/icons8_wifi_connected_100.png
  lib/communication/packet_handler.dart
  lib/communication/science_lab.dart
  lib/communication/socket_client.dart
  lib/others/science_lab_common.dart
  lib/providers/board_state_provider.dart
  lib/providers/locator.dart
  lib/view/connect_device_screen.dart
  lib/view/widgets/main_scaffold_widget.dart
  pubspec.yaml
Labels: Feature, flutter

#2699 feat: Added FAQ page
  lib/constants.dart
  lib/view/faq_screen.dart
  lib/view/widgets/navigation_drawer.dart
Labels: Status: Review Required, flutter

#2729 feat: Ported robotic arm
  lib/communication/science_lab.dart
  lib/constants.dart
  lib/main.dart
  lib/providers/robotic_arm_state_provider.dart
  lib/view/instruments_screen.dart
  lib/view/robotic_arm_screen.dart
  lib/view/widgets/robotic_arm_timeline.dart
  lib/view/widgets/servo_card.dart
  pubspec.yaml
Labels: Status: Review Required, flutter

#2748 refactor: used existing AudioJack in soundmeter
  lib/providers/soundmeter_state_provider.dart
Labels: flutter

#2756 refactor: moved app_theme file to theme folder and moved hardcoded colors to colors file
  lib/colors.dart
  lib/constants.dart
  lib/main.dart
  lib/theme/app_theme.dart
  lib/theme/colors.dart
  lib/theme/typography.dart
  lib/view/accelerometer_screen.dart
  lib/view/connect_device_screen.dart
  lib/view/faq_screen.dart
  lib/view/gyroscope_screen.dart
  lib/view/luxmeter_screen.dart
  lib/view/oscilloscope_screen.dart
  lib/view/robotic_arm_screen.dart
  lib/view/settings_screen.dart
  lib/view/soundmeter_screen.dart
  lib/view/widgets/accelerometer_card.dart
  lib/view/widgets/applications_list_item.dart
  lib/view/widgets/channel_parameters_widget.dart
  lib/view/widgets/common_scaffold_widget.dart
  lib/view/widgets/data_analysis_widget.dart
  lib/view/widgets/gauge_widget.dart
  lib/view/widgets/gyroscope_card.dart
  lib/view/widgets/instruments_stats.dart
  lib/view/widgets/luxmeter_card.dart
  lib/view/widgets/main_scaffold_widget.dart
  lib/view/widgets/navigation_drawer.dart
  lib/view/widgets/oscilloscope_graph.dart
  lib/view/widgets/oscilloscope_screen_tabs.dart
  lib/view/widgets/robotic_arm_timeline.dart
  lib/view/widgets/servo_card.dart
  lib/view/widgets/soundmeter_card.dart
  lib/view/widgets/timebase_trigger_widget.dart
  lib/view/widgets/xyplot_graph.dart
  lib/view/widgets/xyplot_widget.dart
Labels: Status: Review Required, flutter

#2750 feat: added remaining Oscilloscope functionality
  assets/icons/ic_record_white.png
  lib/communication/analytics_class.dart
  lib/constants.dart
  lib/models/oscilloscope_measurements.dart
  lib/providers/oscilloscope_state_provider.dart
  lib/view/oscilloscope_screen.dart
  lib/view/widgets/measurements_list.dart
Labels: Status: Review Required, Feature, flutter
