Repository fossasia/pslab-app, pull requests merged in 2025-03, with the labels that each got.

#2642 fix: ESP01 connection
  app/src/main/java/io/pslab/fragment/ESPFragment.java
  app/src/main/java/io/pslab/fragment/HomeFragment.java
Labels: Fix

#2643 chore: fix release pipeline
  .github/workflows/release.yml
Labels: Chore

#2645 fix: replace non-FLOSS library for 3rd party library screen
  app/build.gradle.kts
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: Dependencies, Fix

#2646 fix: fetch Croller from Maven Central
  app/build.gradle.kts
  libs/croller-release.aar
Labels: Fix

#2650 feat: remove duplicates from 3rd party licenses, add license info of app
  app/build.gradle.kts
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement

#2655 fix: remove duplicate Bluetooth Permissions
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
Labels: Fix

#2657 fix: removed unused Google Maps Key
  gradle.properties
Labels: Fix
