Repository fossasia/pslab-app, pull requests merged in 2025-04, with the labels that each got.

#2651 fix: gyroscope screen crash and UI
  app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
  app/src/main/res/layout/fragment_gyroscope_data.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Review Required, Fix

#2656 fix: accelerometer screen crash and ui
  app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
  app/src/main/res/layout/fragment_accelerometer_data.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Review Required, Fix

#2652 fix: crash in robotic arm activity
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Labels: Status: Review Required, Fix

#2660 docs: 2659 - Did translation to other languages
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/string.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#2663 docs: add string translation for si, ar, pl and ru
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#2667 chore: update screenshots on every push
  .github/actions/screenshot-android/action.yml
  .github/workflows/release.yml
Labels: Chore

#2668 chore: don't use Bundler to execute fastlane
  .github/workflows/release.yml
Labels: Chore

#2640 refactor: update device_filter.xml
  app/src/main/res/xml/device_filter.xml
Labels: Status: Review Required
