Repository fossasia/pslab-app, pull requests merged in 2025-05, with the labels that each got.

#2687 feat: added text input support
  .github/actions/android/action.yml
  lib/others/oscilloscope_axes_scale.dart
  lib/providers/oscilloscope_state_provider.dart
  lib/view/widgets/channel_parameters_widget.dart
  lib/view/widgets/common_scaffold_widget.dart
  lib/view/widgets/data_analysis_widget.dart
  lib/view/widgets/oscilloscope_graph.dart
  lib/view/widgets/timebase_trigger_widget.dart
Labels: Feature, flutter

#2688 chore: use latest SDK to build IPAs
  .github/workflows/pull-request.yml
  .github/workflows/push-event.yml
Labels: Chore, flutter

#2689 fix: rounding error in robotic arm
  app/build.gradle.kts
  app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Labels: Status: Review Required

#2690 fix: Rising Edge Triggering
  lib/providers/oscilloscope_state_provider.dart
  lib/view/connect_device_screen.dart
Labels: Fix, flutter
