Repository fossasia/pslab-app, pull requests merged in 2025-01, with the labels that each got.

#2607 chore: updated pull-request workflow to build debug APK
  .github/actions/android/action.yml
Labels: Chore

#2606 feat: initialized Instruments Screen and Navigation Drawer
  android/app/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  assets/icons/gyroscope_logo.png
  assets/icons/ic_nav_header_logo.png
  assets/icons/ic_usb_disconnected.png
  assets/icons/robotic_arm.png
  assets/icons/thermometer_logo.png
  assets/icons/tile_icon_accelerometer.png
  assets/icons/tile_icon_barometer.png
  assets/icons/tile_icon_compass.png
  assets/icons/tile_icon_gas.png
  assets/icons/tile_icon_horizontal_bars.png
  assets/icons/tile_icon_logic_analyzer.png
  assets/icons/tile_icon_lux_meter.png
  assets/icons/tile_icon_multimeter.png
  assets/icons/tile_icon_oscilloscope.png
  assets/icons/tile_icon_power_source.png
  assets/icons/tile_icon_sensors.png
  assets/icons/tile_icon_vertical_bars.png
  assets/icons/tile_icon_wave_generator.png
  lib/constants.dart
  lib/main.dart
  lib/view/connect_device_screen.dart
  lib/view/faq_screen.dart
  lib/view/instruments_screen.dart
  lib/view/widgets/applications_list_item.dart
  lib/view/widgets/common_scaffold_widget.dart
  lib/view/widgets/navigation_drawer.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: Feature, flutter

#2517 chore: configure automatic screenshots
  .github/actions/screenshot-android/action.yml
  .github/workflows/pull-request.yml
  .github/workflows/push-event.yml
  .github/workflows/release.yml
  app/build.gradle.kts
  app/src/androidTest/java/io/pslab/activity/ScreenshotsTest.java
  app/src/debug/AndroidManifest.xml
Labels: Chore, Status: Review Required

#2561 feat: added support for wireless communication using ESP01
  app/src/main/java/io/pslab/activity/MainActivity.java
  app/src/main/java/io/pslab/communication/CommunicationHandler.java
  app/src/main/java/io/pslab/communication/HttpAsyncTask.java
  app/src/main/java/io/pslab/communication/HttpHandler.java
  app/src/main/java/io/pslab/communication/PacketHandler.java
  app/src/main/java/io/pslab/communication/ScienceLab.java
  app/src/main/java/io/pslab/communication/SocketClient.java
  app/src/main/java/io/pslab/fragment/ESPFragment.java
  app/src/main/java/io/pslab/fragment/HomeFragment.java
  app/src/main/java/io/pslab/interfaces/HttpCallback.java
  app/src/main/java/io/pslab/receivers/WifiDisconnectReceiver.java
  app/src/main/res/drawable/ic_wifi_connected.xml
  app/src/main/res/drawable/icons8_wifi_connected_100.png
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/menu/pslab_connectivity_menu.xml
Labels: Status: Review Required, Feature

#2613 fix: Bluetooth Scan
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
  app/src/main/java/io/pslab/fragment/HomeFragment.java
  app/src/main/java/io/pslab/others/PSLabPermission.java
Labels: Fix

#2615 fix: crash when trying to read data from sensor
  app/src/main/java/io/pslab/sensors/AbstractSensorActivity.java
  app/src/main/java/io/pslab/sensors/SensorADS1115.java
  app/src/main/java/io/pslab/sensors/SensorAPDS9960.java
  app/src/main/java/io/pslab/sensors/SensorBMP180.java
  app/src/main/java/io/pslab/sensors/SensorCCS811.java
  app/src/main/java/io/pslab/sensors/SensorHMC5883L.java
  app/src/main/java/io/pslab/sensors/SensorMLX90614.java
  app/src/main/java/io/pslab/sensors/SensorMPU6050.java
  app/src/main/java/io/pslab/sensors/SensorMPU925X.java
  app/src/main/java/io/pslab/sensors/SensorSHT21.java
  app/src/main/java/io/pslab/sensors/SensorTSL2561.java
  app/src/main/java/io/pslab/sensors/SensorVL53L0X.java
Labels: Bug, Instrument: Sensors

#2621 chore: bump actions/upload-artifact from 3 to 4
  .github/workflows/pull-request.yml
Labels: Chore, Dependencies

#2619 chore: use fastlane-android branch
  .github/workflows/push-event.yml
Labels: Chore, flutter

#2618 chore: bump actions/upload-artifact from 3 to 4
  .github/workflows/pull-request.yml
Labels: Chore, Dependencies, flutter

#2620 chore: use fastlane-android branch
  .github/actions/screenshot-android/action.yml
  .github/workflows/push-event.yml
Labels: Chore

#2617 chore: bump androidx.recyclerview:recyclerview from 1.3.2 to 1.4.0
  app/build.gradle.kts
Labels: Chore, Dependencies, java
